### ISSUE TITLE
Week 2 Day 1 ex 6 question 4 mismatch between result and the one required in audit file

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#26]
When doing this exercise with the current data set I get different values than the ones required in the audit.

<strike>This is probably due to the fact that data being used now contains more recent entries, that were not there at the time of the exercise creation, about a year ago. Since the data-set is being provided by the library it was likely updated with more recent entries by now.</strike> I double-checked and the toy data-sets don't get updated, so it might be something else. Anyway if in the audit is asking for an specific result this should be addressed.

<strike>Perhaps it would be better to provide the data as a file, or to test if the student is accurately getting the expected results in a way that is not dependent on updating the expected values according to new data every given time.</strike>

**Comment by brad-gh** [comment]
The data used is generated and random. We manipulate the dataframe to unstack it so the values are not relevant here. I should mention to check the format and not the values. What do you think ?

**Comment by brad-gh** [comment]
@eslopfer

**Comment by eslopfer** [comment]
Yes, that would solve the issue in my opinion

**Comment by brad-gh** [comment]
[Branch-AI](https://github.com/01-edu/Branch-AI/tree/dev)/[piscine](https://github.com/01-edu/Branch-AI/tree/dev/piscine)/[week01](https://github.com/01-edu/Branch-AI/tree/dev/piscine/week01)/[day04](https://github.com/01-edu/Branch-AI/tree/dev/piscine/week01/day04)/[ex06](https://github.com/01-edu/Branch-AI/tree/dev/piscine/week01/day04/ex06)/[audit](https://github.com/01-edu/Branch-AI/tree/dev/piscine/week01/day04/ex06/audit)/README.md

Pushed on dev. 

@eslopfer  could you please check the audit please ? I don't understand why the second question format is wrong in the preview
