### ISSUE TITLE
Week 2 Day 1 ex1 question 1

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#27]
It's not clear how to audit that question, what does it mean by the output? when I try to return or print the regression I get nothing.

**Comment by brad-gh** [comment]
Usually when a model is fitted (you call the fit method) it outputs the model being fitted, which proves that this is the model we want a fit. 
As suggested for the Logistic Regression, I can check the input code instead of the output.

**Comment by brad-gh** [comment]
pr to be reviewed
