### ISSUE TITLE
Week 2 Day 2 ex 1 question 1

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#28]
When I return or print the logistic regression what I get is `LogisticRegression(random_state=0)`. It's not clear what is meant by return in the audit.

**Comment by brad-gh** [comment]
I can change the audit and instead of validating the output I can check the input code which should be close to: 

```
lr = LogisticRegression(random_state=0)
lr.fit(X,y)
```

What do you think ?

**Comment by brad-gh** [comment]
TODO: Delete Q1 and put the audit as suggestion for Q2

**Comment by brad-gh** [comment]
pr to be reviewed
