### ISSUE TITLE
Week 2 day 5 ex04 Validation curve and learning curve, plot doesn't look the same

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#31]
When trying to solve the first question i get this plot that looks a bit different:

![Screenshot from 2022-08-18 13-17-40](https://user-images.githubusercontent.com/18433970/185392875-1513d9a2-1853-49cb-aaf6-070af9bbd818.png)

I looked at Lee's solution to see if there was something wrong in my approach and his plot is closer to  the one in the audit. By comparing the code I realized that it's using `RandomForestRegressor` instead of what the exercise description appears to suggest to use (`RandomForestClassifier`).

Would that be the reason why the plot looks a bit different? Should I use `RandomForestRegressor` instead?

Also, other than that, if there is some random element in the audit that might make the output not identical, I would suggest to make it explicitly clear.

**Comment by brad-gh** [comment]
Could you explicit what's different ? 
I see the training score that converges towards 1 and the CV score that reaches a plateau around 0.9 after max_depth = 10. The y_lim is 1.1 on the audit, which changes the shape of the plot but not the curves. 

I'm surprised he used RF regressor as this is a classification problem.

**Comment by eslopfer** [comment]
I did it again setting y_lim and it looks closer to what the audit is asking for, but still not identical which could be due to randomness perhaps? Specifically the cross validation score curve it's less steep in my plot before plateauing 
![Screenshot from 2022-09-01 13-51-13](https://user-images.githubusercontent.com/18433970/187918370-d9af726d-b494-4efe-98fd-ca0b9f8ac76c.png)


The learner can't know before looking at the audit file that the plot needs an specific y_lim, would you think it would be reasonable to specify it on the description?

**Comment by brad-gh** [comment]
Add objective comment @brad-gh

**Comment by brad-gh** [comment]
branch dev updated
