### ISSUE TITLE
Week 3 day 1 Ex1 The neuron. Python conventions.

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#32]
As someone new learning python, doing some research regarding naming conventions in python, I found that classes should have the first argument named cls, instances should be self. 

When defining the Neuron Class shouldn’t this convention be applied?

**Comment by brad-gh** [comment]
Good point. This is a best practice, but not mandatory. I'll change it though, thanks.

**Comment by brad-gh** [comment]
pr to be reviewed

**Comment by eslopfer** [comment]
Made comment in the pull request
