### ISSUE TITLE
Week 3 day 2 ex01 Sequential. Inaccurate output.

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#33]
The audit is asking for  `<tensorflow.python.keras.engine.sequential.Sequential object at  xxx`, and I get `<keras.engine.sequential.Sequential at 0x7fc8eb75c8b0>`. 
It would be better to rephrase it as `the output should end with keras.engine.sequential.Sequential at xxx`

**Comment by brad-gh** [comment]
Good point, thanks.
