### ISSUE TITLE
Week 3 day 3 ex 2 The data file is not there and there is no clue where to get it from

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#35]
I managed to get it from plotly datasets, and then checked Lee's solution and that's the one he used. 

It is not clear if that is the data-set or not. A link or some indication of where to get it from, or perhaps providing the actual file could solve this problem.

**Comment by brad-gh** [comment]
Same, I don't know where to put the file> I had sent all the files to Lee, if I remember well. And, it's not a best practice to push them on git.

**Comment by brad-gh** [comment]
[auto-mpg.csv](https://github.com/01-edu/Branch-AI/files/9466535/auto-mpg.csv)

**Comment by davhojt** [comment]
File is pretty small (~400 csv rows). @eslopfer Could you do the same as this: https://github.com/01-edu/Branch-AI/issues/41#issuecomment-1235513036
