### ISSUE TITLE
week 3 day 5  en_core_web_sm and en_core_web_md installation

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#38]
Before being able to use this pipelines they have to be installed. Some indication saying this would be good.

**Comment by brad-gh** [comment]
This [exercice](https://github.com/01-edu/Branch-AI/tree/master/piscine/week03/day05/ex01) asks the student to install the en_core_web_sm. Where can I add the guideline to make it easier ?

**Comment by eslopfer** [comment]
My bad. You are right, It's already saying that.
