### ISSUE TITLE
Week 3 day 5 Different results

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#40]
In this quest there are many exercises where I am getting different results that the ones in the audit file . Don't know if it is because I am doing something wrong, or because the pipelines were updated, or because there is some random component to the result or because of another reason. 

Checking Lee's results, his results are different from mine, and different from the ones in the audit file. So perhaps the reason is randomness in some degree? I think if this is not clear when the learners are about to audit this exercise in the future this will be a source of issues since they won't know how to proceed.

**Comment by brad-gh** [comment]
The embedding could have been updated on the new version. Could you please run the following notebook and tell me and tell me if the results are still different ? 
If they are, this is a good point and I'll update the audit.

**Comment by brad-gh** [comment]
```
import spacy 

nlp = spacy.load("en_core_web_sm")
tokens = nlp("car")

for token in tokens:
    print(token.text, token.has_vector, token.vector_norm, token.is_oov)

token.vector[:20]
```

**Comment by eslopfer** [comment]
![Screenshot from 2022-09-01 13-05-57](https://user-images.githubusercontent.com/18433970/187911364-92a8c5bb-1b16-4034-a947-77a5edb9837d.png)
That's my code. Also for some reason the values in the audit are in scientific notation, But making them into e notation still are different values.

I tried with the code you wrote as well and same exact values as I got in the screenshot

**Comment by brad-gh** [comment]
I set the version of the embedding and udpated the audit on the dev branch
