### ISSUE TITLE
Week 3 day 5 ex6 missing file

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#41]
This exercise can't be solved because the text file is not there, and there aren't any links or hints suggesting how to find it.

**Comment by brad-gh** [comment]
where should the data files should be stored ? Pushing them on Git is not a best practice

**Comment by brad-gh** [comment]
Here is the data [news_amazon.txt](https://github.com/01-edu/Branch-AI/files/9466365/news_amazon.txt)

**Comment by davhojt** [comment]
@brad-gh @eslopfer
The file is pretty small (~2kb). 

We normally keep such files in GitHub. We aim to keep things that are reasonably large outside of GitHub.

**Comment by davhojt** [comment]
I'll put the file at https://github.com/01-edu/Branch-AI/tree/master/piscine/week03/day05/ex06/resources/

**Comment by brad-gh** [comment]
not sure if it was done but I did it on dev
