### ISSUE TITLE
Project 3 Link not working, project moved elsewhere

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#56]
The link `- https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html` takes you to a page that says that the project is abandoned. Also making the link easy to copy with one click is a great idea, but it would be better without the - at the beginning so that it can be directly pastable.

**Comment by brad-gh** [comment]
I'll find another link

**Comment by brad-gh** [comment]
replaced with https://docs.opencv.org/4.x/dd/d43/tutorial_py_video_display.html and PR created

**Comment by eslopfer** [comment]
Thanks, this[#65 ] closes the issue.
