### ISSUE TITLE
Project 4 !!!NO LEAKAGE!!!

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#58]
When trying to understand from the point of view of a learner what is required to be done, I found it difficult to understand what is meant by leakage by reading the document or the small guide provided. I don't remember if this was addressed in the piscine.

When doing a google search I found this definition quite clear: https://en.wikipedia.org/wiki/Leakage_(machine_learning).
Do you think it would be a good idea to add that link to facilitate the task of gathering concepts required as in other parts of the branch? or should it be left to each one to search and find by themselves?

**Comment by brad-gh** [comment]
Yeah I agree when I read the leakage guide I assume they know what's leakage. I'll add your link.

**Comment by brad-gh** [comment]
pushed on dev
