### ISSUE TITLE
Raid 02 Files missing

### ISSUE THREAD

**Issue by eslopfer** [01-edu/Branch-AI#59]
The description is mentioning 3 files: train.csv, test.csv, and covtype.data.
The files are not there.
Also the next line mentions covtype.info, it's not clear if this is a mistake or another file.

**Comment by brad-gh** [comment]
https://drive.google.com/drive/folders/1zN-XFLkDEtKvILxel8PkNqzIYKdTUcPL?usp=sharing

**Comment by brad-gh** [comment]
Typoo fixed + files shared on Drive
